version: '3'

services:
    reverseproxy:
        build:
            context: .
            dockerfile: reverseproxy.Dockerfile
        image: reverseproxy_image
        container_name: reverseproxy_container
        ports:
            - 8080:8080
            - 8081:8081
        restart: always

    bokeh:
        build:
            context: .
            dockerfile: bokeh_image.Dockerfile
        image: bokeh_image
        container_name: bokeh_container
        environment:
            - MH_GMAPS_KEY=$MH_GMAPS_KEY
        volumes:
            - "/Users/alanarvelo/Documents/Manhattan-Heatmap/data:/Manhattan-Heatmap/data:ro"
        restart: always


        # depends_on:
        #   - reverseproxy

# volumes:
#     # "myapp/:myapp/:r"
#   data_folder:
# #     driver: local
